name: evakuvator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  dart_jsonwebtoken: ^2.12.1
  hive:
  hive_flutter:
  flutter_svg: ^2.0.9
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  connectivity_plus: ^4.0.2
  rflutter_alert: ^2.0.7
  sliding_clipped_nav_bar: ^3.1.0+4
  geolocator: ^10.1.0
  url_launcher: ^6.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:



  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
