// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfL27XUMVCTybsezUXbB13XmGdiargzM',
    appId: '1:1049538631244:web:2a7703b9e79070d52ec6e9',
    messagingSenderId: '1049538631244',
    projectId: 'evakuvator',
    authDomain: 'evakuvator.firebaseapp.com',
    storageBucket: 'evakuvator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIaHXZXZfMsYg-Wd4EjrgXK2MetROOEVE',
    appId: '1:1049538631244:android:a85feac5cb46c2bb2ec6e9',
    messagingSenderId: '1049538631244',
    projectId: 'evakuvator',
    storageBucket: 'evakuvator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tlTXQ6lnzjvU-JvTVq00vREkHS6LVh4',
    appId: '1:1049538631244:ios:67f4dfce9ae6613b2ec6e9',
    messagingSenderId: '1049538631244',
    projectId: 'evakuvator',
    storageBucket: 'evakuvator.appspot.com',
    iosBundleId: 'uz.goldapps.evakuvator.evakuvator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tlTXQ6lnzjvU-JvTVq00vREkHS6LVh4',
    appId: '1:1049538631244:ios:393024c68238cf372ec6e9',
    messagingSenderId: '1049538631244',
    projectId: 'evakuvator',
    storageBucket: 'evakuvator.appspot.com',
    iosBundleId: 'uz.goldapps.evakuvator.evakuvator.RunnerTests',
  );
}
